networks:
  proxy:
    name: backbone_proxy
    external: true
  monitoring:
    name: backbone_monitoring
    external: true
  database:
    name: backbone_database
    external: true

services:
  keycloak:
    build:
      context: keycloak
      args:
        KEYCLOAK_VERSION: 26.1.4
        KC_DB: postgres
        KC_FEATURES: "admin-fine-grained-authz"
    container_name: keycloak
    command: start --optimized
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=backbone_proxy
      - traefik.http.routers.keycloak.ruleSyntax=v3
      - traefik.http.routers.keycloak.tls=true
      - traefik.http.routers.keycloak.tls.certresolver=${CERTRESOLVER:-}
      - traefik.http.routers.keycloak.entryPoints=https
      - traefik.http.routers.keycloak.rule=Host("${APPLICATION_FQDN}")
      - traefik.http.routers.keycloak.service=keycloak-service
      - traefik.http.services.keycloak-service.loadbalancer.server.port=8080
      - prometheus.scrape=true
      - prometheus.port=8080
      - prometheus.host=${APPLICATION_FQDN:-} 
    environment:
      TZ: Europe/Berlin
      KC_DB_URL_HOST: ${KEYCLOAK_DB_HOST:-postgres}
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB:-keycloak}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER:-keycloak}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASS:?error}
      KC_DB_SCHEMA: public
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USER:-localadmin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD:?error}
      KC_HOSTNAME: "https://${APPLICATION_FQDN}"
      KC_HTTP_ENABLED: true
      KC_PROXY_TRUSTED_ADDRESSES: "172.16.0.0/12"
      KC_PROXY_HEADERS: "xforwarded"
    networks:
      - proxy
      - database
      - monitoring
